### ISSUE TITLE
Add support for .gql files

### ISSUE THREAD

**Issue by dustyjewett** [jimkyndemeyer/js-graphql-intellij-plugin#134]
defaults for apollo & webpack support both `.graphql` and `.gql` files. This plugin should as well.

(especially since it supports gql tag)

**Comment by marceloverdijk** [comment]
I would like to see support for `.graphqls` extension as well, or probably better make it configurable in the plugin.

I just upgraded from from latest `v1` to `v2 alpha 3` to get support for `"""` descriptors but my `.graphqls` files are not containing highlighting and navigation anymore.

**Comment by jimkyndemeyer** [comment]
You can configure your own file extensions for GraphQL in the File Types page:

![image](https://user-images.githubusercontent.com/15837712/42517471-1085b4aa-8460-11e8-9cbb-c3bba1239d47.png)

v2 of the plugin discontinues `.graphqls`, which was an extension that I introduced in 2016, since the June 2018 GraphQL spec contains SDL.

**Comment by marceloverdijk** [comment]
Thanks @jimkyndemeyer for pointing out the File Types. PS I can't find anything in the spec stating which extension to use.

**Comment by jimkyndemeyer** [comment]
The reason I mentioned the spec was that with SDL as an official part of the GraphQL syntax, there is no need for a separate file extension for schema definitions.
