### ISSUE TITLE
Add support for Framework-specific Schema directives, e.g. Prisma

### ISSUE THREAD

**Issue by pvm** [jimkyndemeyer/js-graphql-intellij-plugin#144]
Hi guys, 

I have a error saying: "Unknown directive @unique", "Unknow directive @default". This directives are used on Prisma.

That's normal or is really a bug?

Thanks

Below is the image of the errors:
![image](https://user-images.githubusercontent.com/2475898/38305756-672183e8-37e4-11e8-9a68-e1da23ef6210.png)

**Comment by jimkyndemeyer** [comment]
Hi Phil.

The plugin is showing this as an error since it has no way to determine the validity of the directives.

It usually determines which directives are available using a configured schema or introspection against an endpoint. But in this case, since you're working on defining your schema, it would have to know the built-in directives given the framework you're using.

I'll keep this issue around as a possible enhancement. For now it's a limitation in the plugin.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha release allow you to declare framework-specific directives as you would any other directive.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
Released https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

**Comment by yaquawa** [comment]
@jimkyndemeyer 
Thank you!
So how to config it to get rid of the error in alpha-3?

**Comment by jimkyndemeyer** [comment]
@yaquawa You declare your framework annotations in a `.graphql` that you place in your project, e.g.:

```graphql
directive @myFrameworkDirective on OBJECT | FIELD_DEFINITION
```

See http://facebook.github.io/graphql/June2018/#sec-Type-System.Directives for reference. The plugin should provide completion for you.

**Comment by yaquawa** [comment]
@jimkyndemeyer 
Perfect! Thanks! 👍🏼
(I didn't even notice that they have a `directive` keyword…)

**Comment by gustawdaniel** [comment]
How to fix highlighting DateTime? I am new in GraphQL. I was trying to type

```
scalar DateTime
```

in `.graphql` file but Web Storm was frozen two times by this.
