### ISSUE TITLE
Graphql files don't have syntax highlighting in RubyMine 2018.1

### ISSUE THREAD

**Issue by vovanmix** [jimkyndemeyer/js-graphql-intellij-plugin#158]
<img width="1142" alt="screen shot 2018-05-20 at 9 12 44 pm" src="https://user-images.githubusercontent.com/7279514/40290400-b18f7cb6-5c72-11e8-91e3-6815a67181d5.png">

**Comment by jimkyndemeyer** [comment]
Hi Vladimir.

Thanks for trying out the plugin.

It's likely that the Node.js language service for the plugin has not been started.

Can you verify your Node.js interpreter has been configured correctly under "Setting"s > "Languages & frameworks" > "Node.js and NPM"? If it's not, please set it up and restart RubyMine.

If that's all in order, and you still don't see the highlighting, please include the console from the GraphQL tool window in RubyMine.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
@vovanmix Nothing actionable from my side before you reply. Closing this for now.

**Comment by frederikhors** [comment]
Same here with Goland 2018.3 and Goland 2018.2 (in 2018.2 many times doesn't work, sometime works! Random!).

**Comment by jimkyndemeyer** [comment]
Issues like this is why V2 of the plugin replaces the external Node.js language service with native code running inside the IntelliJ platform. Less likely to encounter environment and Node.js version issues.

**Comment by Veetaha** [comment]
I have the same issue in **Webstorm 2018.3.1**. No highlight is provided if color settings are inherited from defaults (which are taken from JavaScript highlight rules, where everything is colorized). If I override default setting with ad hoc, highlight works, but I don't want to override them.


<details>
  <summary>What I get when adjusting GraphQL syntax highlight</summary>

  ![link](https://i.imgur.com/c9lQijE.gif)
</details>

<details>
  <summary>What I see in the console</summary>

   ![image](https://user-images.githubusercontent.com/36276403/50127370-8825fc80-0279-11e9-9e51-0c587b1b79ff.png)

</details>

**Comment by mcbain** [comment]
Color support broken in all Jetbrain products. As already stated the color settings are derived from JavaScript which rendern fully colored, where GraphQL one just black/white.

**Comment by jimkyndemeyer** [comment]
Hi all.

I just installed a fresh WebStorm 2018.3.2 and coloring works out of the box:

![image](https://user-images.githubusercontent.com/15837712/51024422-d03ef300-1589-11e9-9367-4ad5735b1064.png)

I suspect this might be related to theming/color scheme settings. What I'd need to proceed is for someone to identify the steps needed to reproduce, starting with a fresh install, e.g. a trial version of WebStorm.

**Comment by jimkyndemeyer** [comment]
@MFoster thanks for the detailed description. It was unclear to me why certain users saw this, and others didn't (including my latest attempt with WebStorm). But I retraced your steps, and was finally able to reproduce.

The issue has to do with class loading and the timing of when the JavaScript syntax highlighter is initialized. If the GraphQL syntax highlighter references the colors before the JS highlighter has assigned the colors, they're simply the default color.

The fix is to reference the JS highlighter class directly from the GraphQL highlighter such that the initialization order of the static color fields are predictable.

My plan is to include this fix in a new release in the near future.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Fixed in v1.7.3 pending JetBrains approval.

Thanks for the help in reproducing. This was a tricky one to pin down.
