### ISSUE TITLE
Template literals support

### ISSUE THREAD

**Issue by GeyseR** [jimkyndemeyer/js-graphql-intellij-plugin#161]
Our team uses template literals for building Apollo GraphQL queries to reduce code duplication.
For example, there are many places in our code where we use the construction like
```
const cmpId = 'EntityField';
const fragment = gql`
  fragment nodeFragment${cmpId} on entity {
    id
    name
  }
`;
const query = gql`
  ${fragment}
  query entityList {
    edges {
      ...nodeFragment${cmpId}
    }
  }
`;
const Component = () => {
  return (
    <ListRenderer query={query} fragment={frament} fragmentId={`nodeFragment${cmpId}`} >
  )
}
```
Apollo and GraphQL plugin work fine with such queries and fragments (execute them or suggesting autocompletion for types), but the plugin also log errors in the console about wrong fragment definition, like
```
Template replacement produced invalid token text range { text: '${cmpId}',
  type: 'template-fragment',
  start: 24,
  end: 33,
  scope: 0,
  kind: 'FragmentDefinition' }
```
Is it possible to fix it somehow and not consider simple string literals expressions as errors?

**Comment by jimkyndemeyer** [comment]
Hi Sergey.

There is already some support for placeholders in template literals at certain locations, including:
- Variables
- Fields
- Top level fragments for Apollo
- Relay classic fragments

The plugin can't support placeholders at arbitrary locations, since you can't express that as a grammar, and produce a valid syntax tree. And you need a syntax tree to be able to run validations and reason about the structure of the code for other language features in the IDE.

Given that all existing GraphQL parsers reject `${}`, this plugin attempts to insert something valid in its place, and then filter out the validation errors that may turn up as a result (e.g. missing selection of non-scalar field that only has a placeholder as a child).

While this approach makes it possible to support the most popular GraphQL client frameworks, it will never be able to handle arbitrary string concatenation.

With all that in mind, my recommendation is to follow the GraphQL spec as close as possible. It's a trade-off, but you get better tooling. I've seen both the Relay team and the Apollo team move in this direction, as it opens up a lot of additional benefits: https://dev-blog.apollodata.com/5-benefits-of-static-graphql-queries-b7fa90b0b69a

Looking at your concrete example, I don't see how this use of placeholders achieves more code reuse than simply referring to the same named fragment from multiple queries like Relay Modern does?

**Comment by GeyseR** [comment]
Hi @jimkyndemeyer 
Thanks for your detailed explanation and reasoning why it's almost impossible (I thought about the same things, but wanted to know your opinion)
Based on the article in Apollo blog, our team will probably re-consider our strategy for using arbitrary strings substitution inside GraphQL query template literals.
