### ISSUE TITLE
Adapt graphql-config format

### ISSUE THREAD

**Issue by schickling** [jimkyndemeyer/js-graphql-intellij-plugin#17]
Would you consider making the project comply to the [graphql-config](https://github.com/graphcool/graphql-config) format?

The goal is the simplify and unify the way people configure their development tools for their GraphQL endpoint/schema.

**Comment by jimkyndemeyer** [comment]
Hi Johannes.

As promised, I've emailed you my thoughts. My recommendation is as follows:

The JSON shape of `request`, and `file` in `graphql.config.json` is unlikely to change. I think this standardized shape should be the thing that various projects agree upon, since they can have various other technical requirements and preferences. A small github repo documenting the shape should do the trick.

So, if `.graphqlrc` is able to reference a `graphql.config.json` file, or any other compliant file, things can work together. I'll leave the naming of the property up to you. Maybe something like:

```
{
 "require": "./graphql.config.json"
}
```

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing this issue. Will create a new issue when the technical details have been worked out.

**Comment by dlindenkreuz** [comment]
@jimkyndemeyer What's the status of this? This feature would be much appreciated.

**Comment by schickling** [comment]
@jimkyndemeyer I'd love to pick up the ball on this one again. Would you be open for a collaboration? 🙂

**Comment by jimkyndemeyer** [comment]
@schickling Yeah, still open to collaborate on this. Unfortunately I don't have any free time to work on features for this project the next three months due to personal commitments.

In the meantime, I'd like to see https://github.com/graphcool/graphql-config/issues/20 resolved. The reason I'd like that issue resolved is that it's a breaking change, and we'd need to figure out a migration path for plugin users. This also ties into the work @asiandrummer is doing on integrating the GraphQL language service with the plugin.

Finally, Relay Modern support provides even more value for developers, so that has higher priority.
