### ISSUE TITLE
Syntax highlighting in GraphQL Strings in JS

### ISSUE THREAD

**Issue by SteveSteinitz** [jimkyndemeyer/js-graphql-intellij-plugin#196]
Hello Jim and JS GraphQL users,

Thanks for sharing this plugin, Jim. 

I confess I'm having difficulty understanding how to use it with an existing project which has GraphQL queries and mutation strings in the .js files.  I've seen mention of a 'Star Wars' demo (I think) but I can't find it.

Anyway, I saw a cool demo for a VSCode plugin in the GraphQL Summit 2018 keynote.  That plugin treats GraphQL query strings (in .js files) as first-class citizens - with syntax highlighting and auto completion.

Can JS GraphQL do that?

**Comment by jimkyndemeyer** [comment]
Hi Steve.

Thanks for trying the plugin.

Yes, when the plugin launched back in 2015 it was aimed at Relay projects that use `Relay.QL` tagged template literals. Since then support was added for Relay Modern (`graphq` tagged template literals) and Apollo projects (`gql` tagged template literals).

When the plugin detects embedded GraphQL strings is enables all language features such as auto completion, error highlighting and go to definition.

A few examples:
- https://twitter.com/jimmeyer/status/774931138976645120 (demos this plugin)
- https://facebook.github.io/relay/docs/en/fragment-container.html#defining-containers
- https://www.apollographql.com/docs/tutorial/queries.html#launches

Hope that helps.

Best regards,
Jim.
