### ISSUE TITLE
Schema from npm module not working

### ISSUE THREAD

**Issue by Lukas-Kullmann** [jimkyndemeyer/js-graphql-intellij-plugin#236]
Our GraphQL API schema is published together with an npm module.
With the new version, it is not possible to load the schema from the module. It always complains that "There is no top level schema object defined". With the old version, it worked just fine.

If I copy the schema file to a place outside the node_modules, it works.
Also, the dialog to "Select GraphQL Schema Base Directory" does not show "node_modules".

## Version and Environment Details
__Operation system__: Ubuntu 18.04.2

__IDE name and version__: IntelliJ 2019.1 Ultimate

__Plugin version__: 2.0.0

**Comment by jimkyndemeyer** [comment]
Hi Lukas.

The plugin searches for schemas within the "Project scope" to avoid searching though 1000s of node modules files.

I was able to get your use case working by right clicking on a node module and choosing "Mark directory as" > "Not excluded". This then places directory within the Project scope and schema discovery picks it up.

Let me know whether this solves your use case.

Best regards,
Jim.

**Comment by Lukas-Kullmann** [comment]
Hi Jim

That worked, thanks! :)

**Comment by medmunds** [comment]
I just ran into the same problem. Even pointing my .graphqlconfig directly at `"schemaPath": "./node_modules/mypackage/schema.graphql"` didn't seem to help.

The workaround I ended up using is linking the node_modules schema into my project files:

```shell
# in the project root dir
ln -s node_modules/mypackage/schema.graphql .
```

One advantage to this workaround is you can commit the symlink in your repository, so it's available to others without needing to share IDE settings.

**Comment by ChrisCrossCrash** [comment]
@medmunds Is it as simple as making the symbolic link in your project root and it just works? I tried making a symbolic link in Windows (using `mklink`), but it doesn't work.

Just for some context:

I also tried the "mark directory as..." option as described by Jim, and that option doesn't exist for me. I'm pretty sure that it's because my project is using the [default behavior for how PyCharm handles the node_modules folder](https://www.jetbrains.com/help/pycharm/2020.3/configuring-javascript-libraries.html#ws_js_libraries_examples_node_modules):

> To provide code completion for project dependencies, PyCharm creates a node_modules library automatically so Node.js modules are kept in your project but no inspections are run against them, which improves performance.

The one way I was able to get it to work was by
1. Marking my `node_modules` folder as "Not Excluded". This makes it not a "library root"
2. Mark `node_modules` as "Excluded"
3. Marking the NPM module that I wanted to import from as "Not Excluded"

However, doing it this way disables the default behavior quoted above. I really don't want to do that.

**Comment by medmunds** [comment]
@ChrisCrossCrash I also have the following .graphqlconfig file in my project root (alongside the schema.graphql symlink that points into node_modules):

```json
{
  "name": "<MyPackage> Schema",
  "schemaPath": "schema.graphql"
}
```

My memory is that graphql-intellij-plugin offered to create the .graphqlconfig file for me once it noticed the schema.graphql symlink, but I could be remembering wrong. You might try creating it yourself if it isn't there. 

(Also, I'm on a Mac, so I created a real symlink using the Unix ln command. When I open schema.graphql in the IDE, I see the content from the linked schema file. I don't know anything about Windows mklink or how it might interact with this plugin or with git.)

**Comment by ChrisCrossCrash** [comment]
@medmunds Thanks for your help, Mike. My project also has the `.graphqlconfig` file. It's the one that gets automatically created when I open the GraphQL plugin tab and click the + button on the left side. It looks like this:
```
{
  "name": "Untitled GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:8000/___graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}
```
The only thing I've changed is the endpoint URL to match what my project is served on.

My project also has the `schema.graphql` file that automatically gets created when I double click on the endpoint listed in the plugin and select the option "Get GraphQL Schema from Endpoint (Introspection)".

The symlinks in Windows appear to work the same way as I'm used to with Linux.

I'm actually having the same exact issue as #295, which links here for a solution.

All of the queries I run within the project work fine. Actually, even the query that's giving me the error `Unknown fragment spread "GatsbyImageSharpFluid"` works, but it just shows an error that can't be ignored.

For now, I've just decided to copy the fragment from the npm module directly into my query. So instead of this:
![image](https://user-images.githubusercontent.com/40023417/103208141-f72a9700-4910-11eb-8dd8-b5b913d6fb80.png)
my query looks like this:
![image](https://user-images.githubusercontent.com/40023417/103208181-0f021b00-4911-11eb-803d-0734baad0317.png)

I think the problem is probably related to how [you can't run these queries in GraphiQL](https://www.gatsbyjs.com/plugins/gatsby-image/#fragments):

> Note, due to a limitation of GraphiQL, you can not currently use these fragments in the GraphiQL IDE.

For now I'll just live with copying and pasting the fragments into my queries. If it's something that end up using a ton, then I'll look into it a bit more.

**Comment by jamendozag** [comment]
Howdy! Any updates on this? Did find a workaround for peer `JetBrain` users, still, its been a while and was hoping there was a fix for this, thanks!!
