### ISSUE TITLE
Support multiples schemas

### ISSUE THREAD

**Issue by sibelius** [jimkyndemeyer/js-graphql-intellij-plugin#27]
I open my webstorm in a top directory that has many projects, some of them use one schema.json and others use another_schema.json, is it possible to make this configurable per folder?

For instance,

projects:
   - projectA
   - projectB

projectA uses schemaA.json
projectB uses schemaB.json

**Comment by jimkyndemeyer** [comment]
Hi Sibelius.

Thanks for using the plugin.

I can see how multiple schemas could be useful in a project. Unfortunately, I think that supporting this would be a rather large change to both the plugin and the language service since they coordinate file watches and editor notifications. A PR that enables this would be very welcome since I'm currently focusing on the Endpoint Language branch.

There is work being done to standardize GraphQL tooling in https://github.com/graphcool/graphql-config so you might want to raise the multiple schemas issue there as well. It's non-trivial since there's also an ongoing discussion about [supporting multiple environments](https://github.com/graphcool/graphql-config/issues/9).

For now, I think your best option is to have multiple WebStorm projects, or edit graphql.config.json when you're working in a specific module.

Best regards,
Jim.

**Comment by sibelius** [comment]
tks, I'll edit for now
