### ISSUE TITLE
Retry loading schema doesn't reload config

### ISSUE THREAD

**Issue by Forever-Young** [jimkyndemeyer/js-graphql-intellij-plugin#277]
## Version and Environment Details
__Operation system__: macOS Mojave

__IDE name and version__: Pycharm 2019.2

__Plugin version__: 2.2.0

## Expected Behaviour
Config has authentication header, when loading schema fails because of stale header, Retry button should reload configuration and use fresh header

## Actual Behaviour
From logs I see that old header values is used. Retry doesn't help, pressing Load schema button (re-run introspection query button)

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Make loading schema fail somehow.
Try to load schema.
It shows Retry
Fix config
Try doing Retry
It still fails

**Comment by jimkyndemeyer** [comment]
Hi Anton.

Thanks for using the plugin.

You should be able to work around this by using environment variables: https://github.com/prisma/graphql-config/blob/master/specification.md#referencing-environment-variables

**Comment by jimkyndemeyer** [comment]
Hi Anton.

I reviewed the "Retry" code paths and they reference a deserialized instance of the endpoint JSON configuration which is why the information is not updated between retry attempts. I don't see an elegant way of fixing this given that endpoint configs aren't guaranteed to be uniquely identifiable between configuration modifications/reloads.

I'll think some more about whether this can be supported, but for now the way to make your use case work is to use environment variables as stated above since their values are resolved on a per-retry basis.

The GitHub API example shows how to use a bearer token from an env variable:
https://github.com/jimkyndemeyer/graphql-config-examples/blob/2cab35b1d1b71f07eeadc345cc43c609dd65a364/github-api-v4/.graphqlconfig#L9

Best regards,
Jim.

**Comment by Forever-Young** [comment]
Yeah, it works good with env variables, thank you.
