### ISSUE TITLE
"Unknown field" error when schema generated using graphql-codegen

### ISSUE THREAD

**Issue by igorakkerman** [jimkyndemeyer/js-graphql-intellij-plugin#286]
Hi,

when I use [GraphQL Code Generator](https://github.com/dotansimha/graphql-code-generator/tree/master/packages/plugins/other/schema-ast) to generate the schema file, some fields cannot be resolved. The error does not appear when creating the schema with this plugin. I tested with the [GitHub API V4](https://api.github.com/graphql).

Schema generated by graphql-codegen:
[github-schema.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/3490467/github-schema.zip)

Schema generated by js-graphql-intellij-plugin:
[github-schema.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/3490470/github-schema.zip)

Example query:
![2019-08-11 23_02_47-github-graphql-lab  C__Lokal_Lab_github-graphql-lab  - GraphQL Fragment (index t](https://user-images.githubusercontent.com/10802670/62839828-ce105480-bc90-11e9-9fe4-ecbb71691d78.png)

Both schemas contain the type `SearchResultItemConnection` with the field `edges`. Any idea what is causing the error?

**Comment by jimkyndemeyer** [comment]
Hi Igor.

Thanks for using the plugin.

The GitHub schema contains emojis in the description of the `enum ReactionContent`. These unicode characters are not valid according to the GraphQL language specification, which is why this plugin and the underlying `graphql-java` can't parse a valid schema. You should see a number of errors in the GraphQL tool window schemas tab such as the following:

![image](https://user-images.githubusercontent.com/15837712/63434405-4ca18a80-c425-11e9-9a92-abf4f5746277.png)

I have reached out to the GitHub team quite a while ago, letting them know that they don't follow the spec. For more information see #216

When you use the plugin to do the introspection it sanitizes issues such as this. The reason that it works in the reference implementation, which GraphQL Code Generator is based on, is that their parser doesn't follow the spec for valid character ranges.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Just got word from the GitHub dev team that they fixed the non-spec issues in their schema. I just introspected it using the plugin and it validates without errors 👍

**Comment by igorakkerman** [comment]
Great to hear, thanks for posting this!
