### ISSUE TITLE
Support directives for Apollo Link modules

### ISSUE THREAD

**Issue by tbinna** [jimkyndemeyer/js-graphql-intellij-plugin#291]
## Version and Environment Details
__Operation system__: 
macOS 10.14.6

__IDE name and version__: 
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

__Plugin version__: 
2.2.0

## Expected Behaviour
Directives in queries for apollo-link-rest (@rest, @export) and apollo-link-state (@client) should not show as errors in queries

## Actual Behaviour
Apollo link queries that include @rest, @export or @client directives produce errors

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

![image](https://user-images.githubusercontent.com/1586709/66538128-a5ec8700-eb55-11e9-9bb5-b867b004a5c2.png)

**Comment by jimkyndemeyer** [comment]
Hi Tobi.

Thanks for using the plugin.

These error markers are intended and valid behavior since the plugin only ships with the standard directives that are part of the GraphQL spec.

For frameworks such as Apollo, or any other, it's up to the developer to declare them. There's an example with `@client` at https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives you can look at.

Once you've declared the directives you also get completion etc.

Best regards,
Jim

**Comment by tbinna** [comment]
Fantastic, thanks for getting back to me @jimkyndemeyer! This worked indeed 👍
