### ISSUE TITLE
Error "tried to redefine existing type" when mixing .graphql and .json schema

### ISSUE THREAD

**Issue by blaugold** [jimkyndemeyer/js-graphql-intellij-plugin#299]
## Version and Environment Details
__Operation system__: 
Ubuntu 19.04

__IDE name and version__: 
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019

__Plugin version__: 
2.2.0

## Expected Behaviour
It should be possible to use sdl to define a schema in one project and a schema.json in another project without having overlapping types conflict with each other.

I use sdl to define a schema implemented by a server in one project and a schema.json file generated from the server in another project for code generation for a client app.

## Actual Behaviour
Types with the same name in different projects produces errors:
```
There is already a schema defined [@1:1].  The offending new new ones is here [@1:1]
'Query' type [@5:1] tried to redefine existing 'Query' type [@5:1]
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

[reproduction repo](https://github.com/blaugold/graphql-js-multi-project-repro)
Just open the project with IntelliJ IDEA.

**Comment by blaugold** [comment]
Adding `include` patterns to all projects resolves the errors in the GraphQL window, but somehow in the editor the types are still being highlighted. Thats only in my project though and I'm not able to reproduce that. Invalidating the cache does not help either.

**Comment by jimkyndemeyer** [comment]
Hi Gabriel.

Thanks for using the plugin.

If you have two separate schemas I recommend that you use two separate `.graphqlconfig` files, one in `a/` and one in `b/`. This way your schemas are automatically fully isolated from each other. The `projects` config field is better suited when you need a shared root folder from which multiple schemas need to include shared types etc.

A `schemaPath` to a JSON file is supported mainly for backwards compatibility, and it's a bit of a tricky implementation since there needs to be a "shadow/in-memory" SDL version based on it. The plugin can introspect a GraphQL endpoint and write a resulting `.graphql` schema file to the `schemaPath` in the config. I suggest you try that as a workaround. See https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection

Let me know if this solves your issue.

Best regards,
Jim.

**Comment by blaugold** [comment]
Hey Jim,

thanks for a great plugin and sorry for the diffuse problem description. Im using [apollo-android](https://github.com/apollographql/apollo-android) to generate code for a client app and their gradle plugin expects a `schema.json` file. SDL files are not supported right now. If I only have SDL schema files in both client and server project directories, overlapping types do not interfere. But I need to include a `schema.json` file generated from the server schema in the client project, for the codegen plugin. It seems like that file is picked up and included in both projects, regardless of include/exclude patterns. 

As a workaround I figured out that renaming the file to something like `schema.__json__` prevents it being detected. My case is probably an edge case and that hack works for me.
