### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by ma-jahn** [jimkyndemeyer/js-graphql-intellij-plugin#304]
Hi,

i've been using this plugin for a while and it's working just fine for me.
But now i'm facing an endpoint with at least two different schemas. A public schema and a protected schema which can only be accessed with a token.

I know i can add custom headers so adding an Authorization Header should be possible. But is there a way to integrate an authentication process?
Something like a before fetch hook would be ideal to send a login call to the defined endpoint and store the token / create an Authorization Header on the fly.

**Comment by jimkyndemeyer** [comment]
Hi Marcel.

Thanks for using the plugin.

There's no such integration planned at this time. The recommendation is to use non-expiring revokable API tokens to authenticate requests. This approach is the most widely used for app-to-app authentication, including GitHub's own GraphQL API, due to its simplicity and predictability.

Best regards,
Jim.
