### ISSUE TITLE
Support multiple schemas for diffrent Template literal tags

### ISSUE THREAD

**Issue by kije** [jimkyndemeyer/js-graphql-intellij-plugin#320]
I'm currently working on a project using gatsby js. There we have a setup, which runs some graphql queries during the static site generation (build time) via gatsby, and some queries are run during runtime (in the browser of the user) via apollo. The runtime queries are run on a different schema than the build time queries.

I have set up my .graphqlconfig with two projects, one for the gatsby graphql endpoint, one for the runtime endpoint:
```json
{
  "name": "Example",
  "projects": {
    "Gatsby": {
      "name": "Gatsby",
      "schemaPath": "schema-gatsby.graphql",
      "include": [
        ",./src/**/*.{ts,tsx}",
        ",./.cache/fragments/*.js",
        ",./node_modules/gatsby-transformer-sharp/fragments.js",
        ",./node_modules/gatsby-*/**/*.js"
      ],
      "extensions": {
        "endpoints": {
          "Gatsby": {
            "url": "http://localhost:8000/___graphql",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    },
    "Runtime": {
      "name": "Runtime",
      "schemaPath": "schema-runtime-api.graphql",
      "include": [
        ",./src/**/*.{ts,tsx}"
      ],
      "extensions": {
        "endpoints": {
          "Runtime": {
            "url": "https://example.com/graphql",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    }
  }
}

```

In my code, both runtime and build time queries can occur in the same file. Runtime queries use the `gql` template literal tag from apollo-client, the build time queries use the `graphql` tag from gatsby.

At the moment, there is no way to configure which schema should be used based on the template literal tag.

**Comment by jimkyndemeyer** [comment]
Hi Kim.

Thanks for using the plugin.

Adding configuration support for this specific use case would complicate project setup, which is why I'm reluctant to go down that path.

I'd recommend you use some kind of file name convention to separate out the two types of GraphQL components you have, and associate them with their respective separate schemas.

As an example, you could name all your Apollo components something like `**/*.runtime.tsx` and set a corresponding `['**/*.runtime.tsx']` glob as `excludes` in your Gatsby project config above.

I realize you would get more component files, but you'd get full tooling support from the plugin, and could simply import your runtime components from the Gatsby components.

Looking at your config file you may have one or more configuration errors:
- `include` should be `includes`
- You're using `,./` in your globs. Don't know what the comma is doing in there, and config files only apply to their current directory and sub-directories in case you meant to write `../` which wouldn't work.

Hope this info is helpful.

Best regards,
Jim
