### ISSUE TITLE
Build error:  Cannot find builtin plugin IntelliLang for IDE

### ISSUE THREAD

**Issue by Flame239** [jimkyndemeyer/js-graphql-intellij-plugin#322]
## Version and Environment Details
__Operation system__:  Mac Os 10.15.3

__IDE name and version__: Intellij IDEA 2019.3.3

__Plugin version__:  -

## Expected Behaviour
Project builds successfully

## Actual Behaviour
Got exception during `gradle build`:
```
FAILURE: Build failed with an exception.


* What went wrong:
A problem occurred configuring root project 'js-graphql-intellij-plugin'.
> Cannot find builtin plugin IntelliLang for IDE: /Users/kirill.andreev/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/LATEST-EAP-SNAPSHOT/9a21016da5663a7e5c72171ab06a4aa51f06b07a/ideaIU-LATEST-EAP-SNAPSHOT
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Clone repo and run `gradle build`

**Comment by Flame239** [comment]
Colleague has the same error on same env

**Comment by jimkyndemeyer** [comment]
This is caused by https://youtrack.jetbrains.com/issue/IDEA-233841

The workaround for now is to update the following line:
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/7845215d9b2d9c927fc118be13a6a4906da990d8/build.gradle#L41

To use a 2019 version, e.g. `'IU-193.6494.35'`

I intend to lock this version down in an upcoming git push, and then use EAP once the above issue has been fixed.

**Comment by jimkyndemeyer** [comment]
Workaround pushed.
