### ISSUE TITLE
including a parent folder seems not to work

### ISSUE THREAD

**Issue by Xample** [jimkyndemeyer/js-graphql-intellij-plugin#336]
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions.

## Version and Environment Details
Mac OS 10.15.1: 

Webstorm 2020.1.1.: 

2.4.0: 

## Expected Behaviour
I expect the following `.graphqlconfig` to recursively include all the schema of the folder it is placed in AND the schemas in the `common`sibling folder

```graphql
{
  "name": "Project A",
  "includes": ["../common/**/*.graphql",  "./**"]
}
```

## Actual Behaviour

The parent folder is not included and the `common` schema will not be found

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
https://github.com/Xample/graphqlconfig-targets-sharing-same-folder

## Workaround:
Create a symbolic link of the common folder into the different projects.

Or possibly add a common .graphqlconfig excluding items instead of adding the one we do want

```graphql
{
  "projects": {
    "A": {
      "name": "Project A",
      "excludes": ["./onlyB/**"]
    },
    "B": {
      "name": "Project B",
      "excludes": ["./onlyA/**"]
    }
  }
}
```

**Comment by jimkyndemeyer** [comment]
Hi Flavien.

Thanks for using the plugin.

It's by design, and not a bug, that you can't use globs that reference files outside the folder that the config file resides in.

The reason for that is that each specific file needs to find the config file that it belongs to in order to see which other files it shares a schema namespace with. The only effective way of doing this is the "current folder + ancestor folders" strategy that graphql config follows.

What you're likely looking for is to use the "projects feature" of graphql config, and then place the config file in a location where it "can see" all relevant files via globs.

See https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/two-schemas-plus-shared-using-projects that demonstrates this.

I'll mark this issue as resolved, but let me know if you have any questions in the comments.
