### ISSUE TITLE
FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'

### ISSUE THREAD

**Issue by sedubois** [jimkyndemeyer/js-graphql-intellij-plugin#34]
Similar to https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/33, I got this message a few times:

`2016-10-17 17:46 node[90149] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'`

**Comment by jimkyndemeyer** [comment]
I need some more information to reproduce this.
- The contents of the editor buffer
- Exact steps to reproduce (are you typing, at what position in the buffer, etc.)

**Comment by sedubois** [comment]
For example this just happened, when I switched in IntelliJ to another Git branch.
Where do I find the editor buffer?

**Comment by jimkyndemeyer** [comment]
Thanks for the info.

By the editor buffer I meant the contents of the current file you're editing in IntelliJ. But I don't think this is relevant to this issue. It might be related to Node.js file system watches:  https://github.com/nodejs/node/issues/854

Is the graphql.config.json file present in one branch and not in the other?

**Comment by sedubois** [comment]
The `graphql.config.json` is in `.gitignore`, so not in VCS.

**Comment by jimkyndemeyer** [comment]
Can you try to run the test case at https://github.com/nodejs/node/issues/854#issuecomment-238922150

Note that some of the Node.js devs can't reproduce the error, but if you're able to, it indicates that the issue is not with the plugin.

**Comment by sedubois** [comment]
Indeed, I can reproduce:

```
$ node test.js 
Watching /Users/sdubois/watchtest
Writing /Users/sdubois/watchtest/foo.txt
Closing watcher
2016-10-17 19:56 node[2079] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```

**Comment by sedubois** [comment]
I constantly get this error now. Is there any way to silence it from plugin side?

**Comment by jimkyndemeyer** [comment]
You should be able to silence it by editing `js-graphql-language-service.dist.js` that the GraphQL node process uses (see its location in the GraphQL console). However, since file watches are broken with your environment setup, the plugin has no way of tracking what's going on with the config, so features such as error highlighting and completion may be broken.

I recommend that you try another Node version while https://github.com/nodejs/node/issues/854 is unresolved.

**Comment by piotrd** [comment]
> However, since file watches are broken with your environment setup, the plugin has no way of tracking what's going on with the config, so features such as error highlighting and completion may be broken.

Does that mean that your plugin is rather unusable currently on macOS @jimkyndemeyer?

**Comment by jimkyndemeyer** [comment]
@piotrd The plugin is fine for use on macOS. My team and myself included uses it daily on both Windows, Linux and macOS.

The issue is with a specific node version and file watches, as outlined in https://github.com/nodejs/node/issues/854. I recommend that you try another Node version while that issue is unresolved.

**Comment by piotrd** [comment]
OK, thank you for clarifying. I may have got it wrong. I am using a different Node version (namely 6.10.1), but I'll try some other to see if it makes a difference.
