### ISSUE TITLE
Add support for repeatable directives

### ISSUE THREAD

**Issue by maraisr** [jimkyndemeyer/js-graphql-intellij-plugin#351]
**Describe the bug**
symbols not defined in the correct order, seem to say they're not defined.

ie;

```
interface Node @source(...) { }

directive @source(...) repeatable on ENUM | OBJECT | INTERFACE | UNION | INPUT_OBJECT | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE
```

Doesn't like that `source` isn't defined—and yet it is.

Which leads me into a second issue;

It doesn't like the `repeatable` keyword used.

**To Reproduce**

1. make the above your schema
2. look at errors

**Expected behavior**
Be happy

**Version and Environment Details**
Operation system: Windows10
IDE name and version: WebStorm 2020.1.3
Plugin version: 2.5.0

**Additional context**

Seems to not like anything defined after it had been used

**Comment by jimkyndemeyer** [comment]
Hi Marais,

Thanks for using the plugin.

This appears to relate to https://github.com/graphql/graphql-spec/pull/472

In essence this means that the grammar for the plugin and also graphql-java needs to be extended.

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/d83dad8bc30b528b6cc9928408ea7e77df6b16bb/src/grammars/GraphQLParser.bnf#L317

graphql-java:
https://github.com/graphql-java/graphql-java/blob/bb87d8f5211f4770934bbca408ca41557d5b4196/src/main/antlr/GraphqlSDL.g4#L124

The reason it's marking `@source` as being undefined is simply due to the directive definition not following the expected grammar, and therefore not being picked up.

There is a bit of work in this because it cuts across grammar + completion in the plugin, and grammar + schema validation in graphql-java.

**Comment by vepanimas** [comment]
A related issue in https://github.com/graphql-java/graphql-java/issues/1763.

**Comment by lorado** [comment]
First - thank you for amazing plugin!
Do you have any updates?  graphql-java seems to have implemented support for `repeatable`

**Comment by vepanimas** [comment]
@lorado hi, I remember about it and plan to implement it during this month.

**Comment by asolopovas** [comment]
Hi guys thanks for the plugin, any updates on this issue?

**Comment by vepanimas** [comment]
@asolopovas hi! I'm working on it right now and plan to fix it this month.

**Comment by stayallive** [comment]
@vepanimas much appreciated 👌

**Comment by stayallive** [comment]
@maraisr Why was this closed? 

AFAIK this is not yet implemented so it would be good to keep this issue open so it can be closed once it is available to prevent people opening up issues to re-request this feature 👍

**Comment by maraisr** [comment]
A baby could have grown from embryo to infant in this time. Software typically moves faster—so I've accepted this as a "won't do" issue. And closed.

**Comment by vepanimas** [comment]
@stayallive @maraisr actually I'm working on it right now. I'm preparing a v3 update in a separate branch https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/v3, where the process of working with a schema is completely reworked, which will help resolve a lot of issues, especially in scenarios when the schema is split between different files. Also, I'm implementing all the missing parts in the spec: descriptions for schema definitions, `extend schema` definitions and repeatable directives. We plan to start testing it this week and release ASAP.

**Comment by stayallive** [comment]
@vepanimas no worries you already said it was coming and I'm assuming that comment was missed by some 👍 

Again many thanks for your work 💪

**Comment by spawnia** [comment]
Working perfectly as of version 3.0, thank you.
