### ISSUE TITLE
Question: schema.js => schema.graphql?

### ISSUE THREAD

**Issue by VikR0001** [jimkyndemeyer/js-graphql-intellij-plugin#367]
My current setup has my schema in a .js file, like this:

```
const typeDefs = `

type InstantMessages {
  id: Int
  from_id: String
  to_id: String
  msgText: String
}
[.....]

schema {
  query: Query,
  mutation: Mutation
  subscription: Subscription
}
`;

export default typeDefs;
```

Then in order to use the schema with Apollo via `swydo-ddp-apollo`, I do this:

```
import AllResolvers from "./api/resolvers";
import AllSchema from "./api/schema";

//APOLLO
import {setup} from 'meteor/swydo:ddp-apollo';

const typeDefs = [AllSchema];
const resolvers = [AllResolvers];

const schema = makeExecutableSchema({
    typeDefs,
    resolvers
});

setup({
    schema
});
```

If I rename schema.js => schema.graphql, I can't export the schema. 

What is the correct way to solve this?

**Comment by vepanimas** [comment]
It seems that this [documentation](https://github.com/apollographql/graphql-tag#importing-graphql-files) has everything you need. You should use your bundler functionality or read a file from the file system directly if this is a server-side code.

**Comment by VikR0001** [comment]
Looking at the docs you kindly linked, it appears they require webpack:

> To add support for importing .graphql/.gql files, see Webpack loading and preprocessing below.

My stack doesn't include webpack. Can I still use `js-graphql-intellij-plugin`?

**Comment by vepanimas** [comment]
@VikR0001 You didn't give any details about your build process, so I'm trying to guess. Looks like you actually use some build tool because I see es6 imports in your code example and they should be processed somehow. Webpack is only an example, it should be implemented for most of the build tools. That one should work for [rollup](https://github.com/kamilkisiela/rollup-plugin-graphql) and this for [babel](https://www.npmjs.com/package/babel-plugin-import-graphql). You can even read a file from the file system manually and pass its contents to the `setup` manually.

This plugin supports this type of [config file] (https://github.com/kamilkisiela/graphql-config/tree/legacy#graphql-config) for now, so the schema must be accessible either from a local file, or be accessible by URL.

**Comment by VikR0001** [comment]
@vepanimas Thanks for this info. The build tool in my stack is [Meteor](https://www.meteor.com/). So if I add [graphql-config](https://github.com/kamilkisiela/graphql-config/tree/legacy#graphql-config), and enter the paths to the relevant files, `js-graphql-intellij-plugin` will use that info?

**Comment by vepanimas** [comment]
@VikR0001 ok, I'm not familiar with meteor myself, but it looks like you should use [this](https://github.com/Swydo/meteor-graphql) package. There is an example of exactly what you want to [implement](https://github.com/Swydo/meteor-graphql#schemas) for a schema loading. After that, you will be able to import from any graphql file in your js files. Then you should move your schema from `.js` file to `schema.graphql`. And the last step is creating `.graphqlconfig` at the root of a project. 

More details about creating a config could be found [here](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide).

**Comment by VikR0001** [comment]
@vepanimas Awesome. This is working. Thanks very much!
