### ISSUE TITLE
Parsing Exception on newly downloaded schema

### ISSUE THREAD

**Issue by SriwanKm** [jimkyndemeyer/js-graphql-intellij-plugin#452]
Steps to Reproduce:

1. Download  Schema
2. Focus on .graphql file with query, as it attempts to parse popups show parse exception

Parsing Errors prevent plugin from functioning normally

Expected:

Can successfully parse and start introspecting and highlighting queries
Latest Version of Plugin, using in Android App on .graphql files

Have been able to manually edit and find a lot of value in the plugin, but in order to increase ease of adoption I would like to find a solution for downloading the schema and parsing smoothly.

Link to Repo with Reproduction or Steps to Reproduce:

**Expected behavior**

**Screenshots**

**Version and Environment Details**
Operation system: [version]
IDE name and version: [version]
Plugin version: [version]

**Additional context**
<img width="1265" alt="Screen Shot 2021-04-20 at 11 18 52 AM" src="https://user-images.githubusercontent.com/47290627/115947476-dbd23180-a495-11eb-8409-b14a6f20f4cf.png">

**Comment by vepanimas** [comment]
Hi @SriwanKm ! Do you still experience this issue? Looks like you had this error due to a default values mismatch. You could skip them  in introspection by choosing this option:
<img width="411" alt="gql-introspect-skip-default-values" src="https://user-images.githubusercontent.com/10243762/139599182-fa67f0b8-80d2-4314-baf5-da49e369d0ae.png">


Actually, I think that we could skip validating default values (at least do not fail schema building completely on conflicting definitions) and remove that option because IMHO it's confusing for the user (as for me, I also always forget why do we have it here 😄). I'm not sure if a default value is a part of the parameter signature, so I'm waiting for the [response](https://github.com/graphql/graphql-js/issues/3214) from the GraphQL team, but I don't think I'll get it ever 😞.

**Comment by vepanimas** [comment]
Closing for no response. Also, I suppose it should be fixed in the most recent release. If it's not the case, please, feel free to reopen.
