### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by binary64** [jimkyndemeyer/js-graphql-intellij-plugin#463]
Just checked out your v3. Because I can't get 2.9.1 working at all. Never build a Java app before. But am hitting this error:

```
C:\Users\User\AppData\Local\Temp\js-graphql-intellij\js-graphql-intellij-plugin>gradlew buildPlugin
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Configuration on demand is an incubating feature.

> Task :generateGraphQLEndpointDocParser FAILED
java.lang.UnsupportedClassVersionError: org/intellij/grammar/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

What's a quick walkthrough to building the .jar files that I can then copy into WebStorm?

Many thanks,

Also,  If you could release v3 that would be awesome 👍

**Comment by vepanimas** [comment]
@binary64 hi! Sorry for the late answer. It seems that this is caused by some incompatibility of the JDKs used. You could check it in the project structure window. I use Jetbrains runtime 11.0.11, Amazon Corretto should be fine too. You can download and install any JDK from the same dropdown if it's missing using "+ Add SDK". There were also some problems with the build process, which I just fixed.

Besides I'm preparing a release right now so I hope it will resolve your issues.

<img width="378" alt="project structure" src="https://user-images.githubusercontent.com/10243762/126379682-03128fcd-c542-4321-9d8e-ff126cd49c6c.png">
<img width="941" alt="intellij-jdk" src="https://user-images.githubusercontent.com/10243762/126379698-8dae26b8-3879-46ec-835b-477111497654.png">
