### ISSUE TITLE
How to configure schema retrieval from a url?

### ISSUE THREAD

**Issue by jahewson** [jimkyndemeyer/js-graphql-intellij-plugin#5]
The readme says that a schema can be retrieved from a local file or a url, however I can't find any examples or documentation showing how to retrieve a schema from a url. How's it work?

**Comment by jimkyndemeyer** [comment]
Hi John.

Once you've generated the `graphql.config.json` from the editor in your IDE, follow the instructions at [graphql.config.json#L9](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/e39cbf18d7178da2e53b48d5316d194f7065fd1a/resources/META-INF/graphql.config.json#L9)

The trick is to remove the "file" property in the config json since it take precedence over the request.

Note that the url can point to a GraphQL endpoint where it posts an introspection query, or it can point at the json from an introspection query. See [graphql.config.json#L11-L14](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/e39cbf18d7178da2e53b48d5316d194f7065fd1a/resources/META-INF/graphql.config.json#L11-L14)

I'll update the docs with examples in the near future. Let me know if you have any questions.

/Jim.

**Comment by jahewson** [comment]
Thanks, everything's working now. Fantastic!
