### ISSUE TITLE
Focus on error window is annoying and hard to work with

### ISSUE THREAD

**Issue by wojciechczerniak** [jimkyndemeyer/js-graphql-intellij-plugin#80]
When schema server is unavailable plugin will try to reconnect over and over again. That's good but every time it gets an error it will focus error window. It's hard to start dev server because dev server is not started 😉 Is there a way to disable focusing GraphQL plugin window on error?

Version: 1.5.2

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for using the plugin.

There's no option for this currently. I'd be happy to accept a PR that adds an options page for this plugin (don't have free time to work on it atm).

Thanks,
Jim.

**Comment by jimkyndemeyer** [comment]
Hi.

Been trying to reproduce this with no luck. It appears to be the same as #90.

Can you provide more details on your setup, steps to reproduce, graphql.config.json etc.

Also, which IDE are you using, and what version.

Thanks,
Jim.

**Comment by jimkyndemeyer** [comment]
Seeing as the underlying cause for this issue is unclear, and I'm unable to reproduce, I've included a fix in 1.5.4 that only shows the console automatically on the first project error.

Just released to the plugin repository, and pending JetBrains approval (typically 1-2 business days).

Feel free to add a comment if you find additional info to help reproduce.
