### ISSUE TITLE
Support for multiple schemas (on multiple endpoints)

### ISSUE THREAD

**Issue by estaub** [jimkyndemeyer/js-graphql-intellij-plugin#84]
I need to access two different graphql endpoints from a project, where each endpoint has a different schema.  

I'm currently keeping two different copies of graphql.config.json that I swap between as needed. 

Is there a better way to handle this?  If not, consider this an enhancement request.

**Comment by jimkyndemeyer** [comment]
There's no support for this at the moment. I suggest you have two scripts that copy to graphql.confg.json which is watched by the plugin.

**Comment by hsyed** [comment]
I just hit this one as well, working on a storage backend that has multiple schemas. It would be very useful to pair the schema with the endpoint in some way.

**Comment by yuricamara** [comment]
Has anyone tried merging with lodash or something else?

I wrote this code but it doesn't merge as expected.

```
'use strict';
const { merge } = require('lodash');

const fs = require('fs');

const schemasClosed = require('../src/graphql/schemas/schemas.closed.json');
const schemasOpened = require('../src/graphql/schemas/schemas.opened.json');
const schemasRestricted = require('../src/graphql/schemas/schemas.restricted.json');

const schemas = merge(schemasClosed, schemasOpened, schemasRestricted);
const schemasToString = JSON.stringify(schemas);

fs.writeFile('src/graphql/schemas/schemas.json', schemasToString, (err) => {
  if (err) throw err;
  console.log('The file has been saved!');
});
```

**Comment by Epenance** [comment]
Would indeed be amazing to have, I have several endpoints, that i would love to have support for rather than having to update my config all the time when i change between them.

**Comment by stonecold123** [comment]
I've already set to get the schema from an url endpoint. Now I want to use apollo link state to manage local store, but I don't know how to make the plugin to get a .graphql schema file for local store as well.

**Comment by ph55** [comment]
Same here.
Working with mono-repository approach.
So the schema is different per endpoint.

My thoughts about architecture:
* Schema could be set per endpoint.
![image](https://user-images.githubusercontent.com/1386622/40001139-32e3f58a-5796-11e8-9f20-69c52bf6ee66.png)


* `graphql.config.json` could be placed in many directories in project.
![image](https://user-images.githubusercontent.com/1386622/40001174-48075196-5796-11e8-8a5e-3f8d465a3cfa.png)

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha makes it possible to have multiple schemas in a single project using IntelliJ/WebStorm "Scopes". You can configure them for the project in the IDE Settings dialog.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
I'll quickly outline how to set it up.

The schemas are kept apart using the "Scopes" feature in your IDE:

![image](https://user-images.githubusercontent.com/15837712/41645629-cd5726c6-7471-11e8-876e-9d859a22bc86.png)

For this example, I've added a single scope, and clicked the "src" folder, followed by "Include recursively".

As you work with GraphQL in the editor, the file you're in will be matched against the scopes, and the first match limits which schema type definitions etc. that are included.

Hope that clears things up.

I plan on creating a GraphQL-specific dialog for scopes such that users are free to use these generic scopes for other use cases.

**Comment by jimkyndemeyer** [comment]
See https://github.com/jimkyndemeyer/graphql-config-examples for examples of how to configure multiple schemas with v2 of the plugin.

**Comment by petr-ujezdsky** [comment]
Hi,

I am unable to "link" 4 projects together properly.
@jimkyndemeyer Could you please help me with the proper configuration?
My project looks like this
```
api1
└── src
    └── main
        └── resources
            ├── .graphqlconfig
            └── mySchema.graphqls

api2
└── src
    └── main
        └── resources
            ├── .graphqlconfig
            └── mySchema.graphqls

application1
└── src
    └── myComponent.jsx

application2
└── src
    └── myComponent.jsx
```

Where `application1` uses `api1` and `application2` uses `api2`.
Both api run at different ports.

`.graphqlconfig` for api1:
```
{
  "name": "Api1 GraphQL Schema",
  "schemaPath": "mySchema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:8081/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}

```
`.graphqlconfig` for api2:
```
{
  "name": "Api2 GraphQL Schema",
  "schemaPath": "mySchema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:8082/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}

```

The "link" between `application1` and `api1` works flawlessly. I can click-through `gql` queries and their containing types from `myComponent.jsx` into `myScheme.graphql`. It also autocompletes fields inside queries.
However in `application2` all queries and types are "linked" to `api1` schema - when I click-through query / contained type I am navigated into schema inside `api1` instead of inside `api2`.
Strange thing is that query defined only inside `api2` is recognised properly and I am navigated to it. But Idea has no autocomplete options inside this query and every field is red.

I have looked at the `projects` section of `.graphqlconfig` but I do not know how to "link" them to their related application.
I tried to create only one `.graphqlconfig` in project root (with just one endpoint for now):
```
{
  "name": "Apis GraphQL Schema",
  "projects": {
    "api1": {
      "schemaPath": "api1/src/main/resources/mySchema.graphqls",
      "includes": ["api1/**", "application1/**"]
    },
    "api2": {
      "schemaPath": "api2/src/main/resources/mySchema.graphqls",
      "includes": ["api2/**", "application2/**"]
    }
  },
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://sokol.local:8082/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}

```
But Idea did not recognise that. Idea expects to have this file in `resources` folder as I currently have. It even suggests to create new one there while you click on the wrench icon on top of `mySchema.graphqls`.

**Comment by jimkyndemeyer** [comment]
@petr-ujezdsky You're on the right track with the projects-based configuration since your schemas span folders at the same levels in the file system. I'm not sure what you mean by the resources folder, but the graphql config needs to be in the same or a parent directory to anything that it matches in the `includes`. For each file, looking for a config in the current directory and any parent directories is how each file is then associated back to the config, meaning that it logically belongs to that project schema.

The example at https://github.com/jimkyndemeyer/graphql-config-examples/blob/master/two-schemas-plus-shared-using-projects is pretty close to what you're trying to do. Maybe there's a clue there as to why your config isn't working.

**Comment by Blindpupil** [comment]
For sometime I had it working like this and it would generate a core.schema and content.schema correctly, but after moving to the new format with .yml it doesn't work anymore.

```
{
  "name": "MyApp GraphQL Schema",
  "extensions": {
    "endpoints": {
      "schemaPath": "core.graphql",
      "core": {
        "url": "http://localhost:4000/q",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      },
      "content": {
        "schemaPath": "content.graphql",
        "url": "http://localhost:3000/content/q",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  },
  "projects": {
    "myApp": {
      "schema": ["core.graphql", "content.graphql"]
    }
  }
}
```

This is the new grahpql.config.yml that doesn't work: 
```
projects:
  myApp:
extensions:
  endpoints:
    core:
      schemaPath: core.graphql
      url: http://localhost:4000/q
      headers:
        user-agent: JS GraphQL
      introspect: true
    content:
      schemaPath: content.graphql
      url: http://localhost:3000/content/q
      headers:
        user-agent: JS GraphQL
      introspect: true
schema: [core.graphql, content.graphql]
```

**Comment by jimkyndemeyer** [comment]
@Blindpupil Please log a new issue which includes the version of the plugin you're using. This is a very old thread for 1.x of the plugin. Thanks.
