### ISSUE TITLE
Step-by-step doc installation for this plugin

### ISSUE THREAD

**Issue by jdorleans** [jimkyndemeyer/js-graphql-intellij-plugin#97]
Please provide a step-by-step doc installation for this plugin. For those who are not very familiar with JS it isn't very clear which dependencies and versions to install and how to configure them in Intellij.

**Comment by jimkyndemeyer** [comment]
Hi Jonathan.

Thanks for trying out the plugin.

I'll update the FAQ on the front page to make it more clear.

For now, what you need to do is the following inside your IDE (e.g. IntelliJ, WebStorm etc.):

- Open "Settings", "Plugins", "Browse repositories..." and search for "Node.js" and click install.
- In the same "Browse repositories" screen search for "GraphQL" and click install.
- Follow the instructions to restart your IDE

That's it. I hope the FAQ answers any other questions you might have, e.g. configuring the schema. Otherwise, let me know.

/jim.

**Comment by jdorleans** [comment]
@jimkyndemeyer please, check on #99

**Comment by jimkyndemeyer** [comment]
The 2.0 release has a dedicated documentation site at https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/getting-started which covers installation.
